export interface Weighted {
  value: string;
  weight: number;
}

// 40 hobbies with skewed weights so the top-20 list has meaningful, uneven counts.
export const HOBBIES: Weighted[] = [
  { value: 'Reading', weight: 10 },
  { value: 'Cooking', weight: 9 },
  { value: 'Hiking', weight: 9 },
  { value: 'Photography', weight: 8 },
  { value: 'Gaming', weight: 8 },
  { value: 'Traveling', weight: 8 },
  { value: 'Swimming', weight: 7 },
  { value: 'Cycling', weight: 7 },
  { value: 'Running', weight: 7 },
  { value: 'Yoga', weight: 6 },
  { value: 'Painting', weight: 6 },
  { value: 'Gardening', weight: 6 },
  { value: 'Chess', weight: 5 },
  { value: 'Dancing', weight: 5 },
  { value: 'Fishing', weight: 5 },
  { value: 'Baking', weight: 5 },
  { value: 'Singing', weight: 4 },
  { value: 'Writing', weight: 4 },
  { value: 'Camping', weight: 4 },
  { value: 'Climbing', weight: 4 },
  { value: 'Surfing', weight: 3 },
  { value: 'Skiing', weight: 3 },
  { value: 'Knitting', weight: 3 },
  { value: 'Pottery', weight: 3 },
  { value: 'Archery', weight: 2 },
  { value: 'Astronomy', weight: 2 },
  { value: 'Birdwatching', weight: 2 },
  { value: 'Calligraphy', weight: 2 },
  { value: 'Fencing', weight: 2 },
  { value: 'Juggling', weight: 2 },
  { value: 'Kayaking', weight: 2 },
  { value: 'Magic', weight: 1 },
  { value: 'Origami', weight: 1 },
  { value: 'Parkour', weight: 1 },
  { value: 'Quilting', weight: 1 },
  { value: 'Robotics', weight: 1 },
  { value: 'Sculpting', weight: 1 },
  { value: 'Skateboarding', weight: 1 },
  { value: 'Woodworking', weight: 1 },
  { value: 'Beekeeping', weight: 1 },
];

// ~30 nationalities with skewed weights so 10+ fall outside the top 20.
export const NATIONALITIES: Weighted[] = [
  { value: 'American', weight: 10 },
  { value: 'Chinese', weight: 9 },
  { value: 'Indian', weight: 9 },
  { value: 'British', weight: 8 },
  { value: 'German', weight: 8 },
  { value: 'French', weight: 7 },
  { value: 'Japanese', weight: 7 },
  { value: 'Brazilian', weight: 6 },
  { value: 'Canadian', weight: 6 },
  { value: 'Australian', weight: 5 },
  { value: 'Italian', weight: 5 },
  { value: 'Spanish', weight: 5 },
  { value: 'Mexican', weight: 4 },
  { value: 'Korean', weight: 4 },
  { value: 'Dutch', weight: 4 },
  { value: 'Swedish', weight: 3 },
  { value: 'Polish', weight: 3 },
  { value: 'Turkish', weight: 3 },
  { value: 'Egyptian', weight: 3 },
  { value: 'Nigerian', weight: 3 },
  { value: 'Argentine', weight: 2 },
  { value: 'Vietnamese', weight: 2 },
  { value: 'Thai', weight: 2 },
  { value: 'Greek', weight: 2 },
  { value: 'Portuguese', weight: 2 },
  { value: 'Norwegian', weight: 1 },
  { value: 'Finnish', weight: 1 },
  { value: 'Irish', weight: 1 },
  { value: 'Swiss', weight: 1 },
  { value: 'Kenyan', weight: 1 },
];
